name: Example Workflow

on:
  workflow_dispatch:

env:
  API_KEY: ${{ secrets.TMDB_API_KEY }}

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use secret in environment variable
        run: |
          pip install requirements
          streamlit run app.py
